// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wlogxlzhbtrhjarvmyvu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indsb2d4bHpoYnRyaGphcnZteXZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwOTk1NzcsImV4cCI6MjA2NTY3NTU3N30.VBS0gcjN9Xbm_RH2ijwAUJFl6kfFrhiZh3FqVn1KAc0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);